### ISSUE TITLE
Add bigscoots-staging.com to staging sites list

### ISSUE THREAD

**Issue by wormeyman** [rosswintle/turbo-admin#31]
Please add bigscoots-staging.com to the staging sites list, the ability to add custom ones would be helpful as well. The format they use is https://account-namecom.bigscoots-staging.com/wp-admin/

**Comment by rosswintle** [comment]
Hi Eric,

Thanks for this. This repository is actually for the plugin version which doesn't have this feature, so I'll copy this across to the (private) repo for the extension.

I'll get this added to the list at some point. It will be in a future release.

Making the dev/staging sites list customisable is a good idea, but would need me to add a full settings "page" rather than just the pop-up.

Given there is a command palette in WordPress core now (although, a very "alpha" version of one in my opinion) I'm not sure that I'll be doing _major_ development of Turbo Admin.

We'll see.

Thanks again.

Ross

**Comment by rosswintle** [comment]
Moved to https://github.com/rosswintle/turbo-admin-extension/issues/105
